baseURL = "https://seleniums.top/"
title = "Selenium Lab | Tech & Security"
theme = "PaperMod"

[params]
    env = "production"
    description = "Deep dives into system customization, web dev, and cybersecurity."
    # PaperMod Specifics
    ShowReadingTime = true
    ShowShareButtons = true
    ShowToc = true           # Good for long technical guides
    TocOpen = false          # Keeps the UI clean on mobile

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    lineNos = true           # Professionals love line numbers
    style = "monokai"        # Dark, tech-focused code style