baseURL = 'https://seleniums.top/'
languageCode = 'en-us'
title = 'Selenium Lab'
theme = 'PaperMod'
enableRobotsTXT = true

[params]
    env = 'production'
    description = 'Tech blogging, Windows customization, and Cybersecurity insights.'
    ShowReadingTime = true
    ShowShareButtons = true
    ShowToc = true
    # ... your other params ...
    customCSS = ["css/extended.css"]

    [params.homeInfoParams]
        Title = "Welcome to Selenium Lab"
        Content = "Exploring High-quality beautiful wallpaper in 4K"

    # We use a custom name here to avoid the "author" keyword conflict
    [params.profile]
        name = "Kawsar"
        bio = "Cybersecurity student and tech enthusiast."

[params.assets]
    favicon = "images/favicon.ico"
    favicon16x16 = "images/favicon.ico"
    favicon32x32 = "images/favicon.ico"
    apple_touch_icon = "images/favicon.ico"

[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 10

[[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 20

[[menu.main]]
    name = "News"
    url = "/news/"
    weight = 30
